### ISSUE TITLE
AJAX scripts may lack permissions tests

### ISSUE THREAD

**Issue by mudrd8mz** [NMAI-lab/moodle-mod_socialwiki#32]
I may be missing something but it seems that AJAX call handlers like `like.php` are missing access control and sesskey tests. Additionally, these scripts should define the constant `AJAX_SCRIPT`.

**Comment by bencroskery** [comment]
Looking at the code I'm not entirely sure how to implement these changes. It's hard to find any documentation on either the sesskey or the AJAX_SCRIPT.

At the moment the code is combined in like.php to support the like button with and without javascript using JQuery.
The only code I've seen using a sesskey in js also uses YUI, which I would prefer to stay away from as you guys are phasing it out. I've read the javascript AJAX in MoodleDocs but I think a web service is overkill for a simple but that just gives the user a little feedback.
Also adding AJAX_SCRIPT stops allowing a page refresh, meaning that the non-javascript implementation stops working. From what I can tell, a second like.php without AJAX with almost the exact same code would have to be created to compensate.

**Comment by mudrd8mz** [comment]
https://docs.moodle.org/dev/Security:Cross-site_request_forgery

And yes. It is the pattern in Moodle that there are distinct end-point scripts for AJAX and non-AJAX access. Of course, it is wise to organise the code so that they both access the same library functions/methods etc.

See https://docs.moodle.org/dev/AJAX_pre_2.9 and https://docs.moodle.org/dev/AJAX

**Comment by bencroskery** [comment]
Is the new way of handling AJAX in 2.9 backwards compatible down to Moodle 2.6?

I've gotten the sesskey working now, but the AJAX_SCRIPT constant seems to stop the comfirm_sesskey from working in my ajax php file.
Right now the sesskey is just being passed to javascript then passed as a parameter to the ajax php file. I haven't seen it done this way so I feel the sesskey doesn't get passed correctly when the php file is an AJAX script.

**Comment by bencroskery** [comment]
I've finally got the AJAX_SCRIPT working. Looking through the moodle core code I realized that I had to return the data encoded in JSON, otherwise the script would not work properly.

I will got ahead and upload a new version to the Moodle plugin directory in a few hours as I believe any problems have been fixed.
Next I'll get to work writting the Behat tests for the plugin. From what I can tell these aren't required so it would be great if the plugin could be validated before I go through and make a bunch of them.
