### ISSUE TITLE
Follow similarity with another user decreases when you follow them

### ISSUE THREAD

**Issue by bencroskery** [NMAI-lab/moodle-mod_socialwiki#35]
When you follow a user, the similarity between your follows will decrease. This shouldn't affect the similarity as the user doesn't have the option to follow themselves (and they probably would if they could).
I assume that the current user following another user as well as another user following the current user would both decrease the follow similarity. I believe there are two options here.
1. Stop the similarity calculation from including the two users that are being compared.
2.  Potentially have the user actually follow themselves by default hidden in the database, as people who follow each other are probably more interested in what the other is creating (although this then goes the other way decreasing the similarity if they don't follow each other).

**Comment by esfandia** [comment]
Option 2 could create a whole bunch of side effects, and you might have to write "if" statements all over the place to exclude ranking yourself as the most similar person to yourself, etc. and so my preference is probably Option 1. I can also live with the status quo, because strictly speaking it is correct, just not intuitive.
