### ISSUE TITLE
Migrate demo node to latest Moodle

### ISSUE THREAD

**Issue by esfandia** [NMAI-lab/moodle-mod_socialwiki#55]
I wonder if the bug #54 I reported earlier is still a bug in the more recent versions of Moodle. It might be good migrating that demo node to run the latest version, since we're comfortable hosting actual courses on it anyway. Not sure how much work it is to migrate the content of the demo wikis...

**Comment by bencroskery** [comment]
The bug was for all Moodle versions, but I agree it would be a good idea to upgrade to the latest Moodle. I had previously migrated the content onto the newer server and it was a fairly simple process so upgrading the system should not be too big of an issue.

On the other hand, this server has not been updated yet to fix bug #54 as there seems to be a git issue stopping it from updating to the most recent version.

**Comment by esfandia** [comment]
I think this can be closed now, but I'll leave it up to you! :)

**Comment by bencroskery** [comment]
The server seems to be working no problem now so I think it can be closed too
